sub_map = {
    'begin_of_file': '',
    'end_of_file': '',
    't_K_ABORT': 'ABORT',
    't_K_ACTION': 'ACTION',
    't_K_ADD': 'ADD',
    't_K_AFTER': 'AFTER',
    't_K_ALL': 'ALL',
    't_K_ALTER': 'ALTER',
    't_K_ANALYZE': 'ANALYZE',
    't_K_AND': 'AND',
    't_K_AS': 'AS',
    't_K_ASC': 'ASC',
    't_K_ATTACH': 'ATTACH',
    't_K_AUTOINCREMENT': 'AUTOINCREMENT',
    't_K_BEFORE': 'BEFORE',
    't_K_BEGIN': 'BEGIN',
    't_K_BETWEEN': 'BETWEEN',
    't_K_BY': 'BY',
    't_K_CASCADE': 'CASCADE',
    't_K_CASE': 'CASE',
    't_K_CAST': 'CAST',
    't_K_CHECK': 'CHECK',
    't_K_COLLATE': 'COLLATE',
    't_K_COLUMN': 'COLUMN',
    't_K_COMMIT': 'COMMIT',
    't_K_CONFLICT': 'CONFLICT',
    't_K_CONSTRAINT': 'CONSTRAINT',
    't_K_CREATE': 'CREATE',
    't_K_CROSS': 'CROSS',
    't_K_CURRENT_DATE': 'CURRENT_DATE',
    't_K_CURRENT_TIME': 'CURRENT_TIME',
    't_K_CURRENT_TIMESTAMP': 'CURRENT_TIMESTAMP',
    't_K_DATABASE': 'DATABASE',
    't_K_DEFAULT': 'DEFAULT',
    't_K_DEFERRABLE': 'DEFERRABLE',
    't_K_DEFERRED': 'DEFERRED',
    't_K_DELETE': 'DELETE',
    't_K_DESC': 'DESC',
    't_K_DETACH': 'DETACH',
    't_K_DISTINCT': 'DISTINCT',
    't_K_DROP': 'DROP',
    't_K_EACH': 'EACH',
    't_K_ELSE': 'ELSE',
    't_K_END': 'END',
    't_K_ESCAPE': 'ESCAPE',
    't_K_EXCEPT': 'EXCEPT',
    't_K_EXCLUSIVE': 'EXCLUSIVE ',
    't_K_EXIST': 'EXIST',
    't_K_EXPLAIN': 'EXPLAIN',
    't_K_FAIL': 'FAIL',
    't_K_FOR': 'FOR',
    't_K_FOREIGN': 'FOREIGN',
    't_K_FROM': 'FROM',
    't_K_FULL': 'FULL',
    't_K_GLOB': 'GLOB',
    't_K_GROUP': 'GROUP',
    't_K_HAVING': 'HAVING',
    't_K_IF': 'IF',
    't_K_IGNORE': 'IGNORE',
    't_K_IMMEDIATE': 'IMMEDIATE',
    't_K_IN': 'IN',
    't_K_INDEX': 'INDEX',
    't_K_INDEXED': 'INDEXED',
    't_K_INITIALLY': 'INITIALLY',
    't_K_INNER': 'INNER',
    't_K_INSERT': 'INSERT',
    't_K_INSTEAD': 'INSTEAD',
    't_K_INTERSECT': 'INTERSECT',
    't_K_INTO': 'INTO',
    't_K_IS': 'IS',
    't_K_ISNULL': 'ISNULL',
    't_K_JOIN': 'JOIN',
    't_K_KEY': 'KEY',
    't_K_LEFT': 'LEFT',
    't_K_LIKE': 'LIKE',
    't_K_LIMIT': 'LIMIT',
    't_K_MATCH': 'MATCH',
    't_K_NATURAL': 'NATURAL',
    't_K_NO': 'NO',
    't_K_NOT': 'NOT',
    't_K_NOTNULL': 'NOTNULL',
    't_K_NULL': 'NULL',
    't_K_OF': 'OF',
    't_K_OFFSET': 'OFFSET',
    't_K_ON': 'ON',
    't_K_OR': 'OR',
    't_K_ORDER': 'ORDER',
    't_K_OUTER': 'OUTER',
    't_K_PLAN': 'PLAN',
    't_K_PRAGMA': 'PRAGMA',
    't_K_PRIMARY': 'PRIMARY',
    't_K_QUERY': 'QUERY',
    't_K_RAISE': 'RAISE',
    't_K_RECURSIVE': 'RECURSIVE',
    't_K_REFERENCES': 'REFERENCES',
    't_K_REGEXP': 'REGEXP',
    't_K_REINDEX': 'REINDEX',
    't_K_RELEASE': 'RELEASE',
    't_K_RENAME': 'RENAME',
    't_K_REPLACE': 'REPLACE',
    't_K_RESTRICT': 'RESTRICT',
    't_K_RIGHT': 'RIGHT',
    't_K_ROLLBACK': 'ROLLBACK',
    't_K_ROW': 'ROW',
    't_K_SAVEPOINT': 'SAVEPOINT',
    't_K_SELECT': 'SELECT',
    't_K_SET': 'SET',
    't_K_TABLE': 'TABLE',
    't_K_TEMP': 'TEMP',
    't_K_TEMPORARY': 'TEMPORARY',
    't_K_THEN': 'THEN',
    't_K_TO': 'TO',
    't_K_TRANSACTION': 'TRANSACTION',
    't_K_TRIGGER': 'TRIGGER',
    't_K_UNION': 'UNION',
    't_K_UPDATE': 'UPDATE',
    't_K_UNIQUE': 'UNIQUE',
    't_K_USING': 'USING',
    't_K_VACUUM': 'VACUUM',
    't_K_VALUES': 'VALUES',
    't_K_VIEW': 'VIEW',
    't_K_VIRTUAL': 'VIRTUAL',
    't_K_WHEN': 'WHEN',
    't_K_WHERE': 'WHERE',
    't_K_WITH': 'WITH',
    't_K_WITHOUT': 'WITHOUT',
    't_STRING_LITERAL': '\'\'',
    't_NUMERIC_LITERAL': '1',
    't_BLOB_LITERAL': 'X\'a\''
}


def sub(lines):
    for i, l in enumerate(lines):
        subbed = l
        for key in sub_map:
            subbed = subbed.replace(key, sub_map[key])
        lines[i] = subbed
    return lines


if __name__ == '__main__':
    f = open('out/sql.test', 'r')
    lines = f.readlines()
    for i, l in enumerate(lines):
        subbed = l
        for key in sub_map:
            subbed = subbed.replace(key, sub_map[key])
        lines[i] = subbed
    f.close()
    f = open('out/sql.test', 'w')
    f.writelines(lines)
    f.close()
